name: Continuous Integration
on:
  push:
  pull_request:
  release:
    types: [created]
jobs:
  lint-and-build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '21.7'
        registry-url: 'https://registry.npmjs.org'
    - run: npm ci
    - run: npm run-script lint
    - run: npm run-script build
  release:
    if: github.event_name == 'release' && github.event.action == 'created'
    needs: lint-and-build
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '21.7'
        registry-url: 'https://registry.npmjs.org'
    - run: npm ci
    - run: npm run-script build
    - run: echo //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }} > ${NPM_CONFIG_USERCONFIG}
    - run: "sed -i \"s/\\\"version\\\": \\\"0.0.0\\\",/\\\"version\\\": \\\"${GITHUB_REF/refs\\/tags\\/v/}\\\",/g\" package.json"
    - run: npm publish --access public
